import NavigationBar from './components/NavigationBar';
import './global.css';
import StoreProvider from './StoreProvider';

export const metadata = {
  title: 'Welcome to food-blog-client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className="bg-gray-50 text-gray-900 font-sans">
          <header className="sticky top-0 z-50 bg-gradient-to-b  from-light-sand to-warm-beige">
            <NavigationBar></NavigationBar>
          </header>
          <div>{children}</div>
        </body>
      </StoreProvider>
    </html>
  );
}
