import NavigationBar from '../components/NavigationBar';
import './global.css';
import StoreProvider from '../components/StoreProvider';
import { Montserrat } from 'next/font/google';

export const metadata = {
  title: 'Welcome to food-blog-client',
  description: 'Generated by create-nx-workspace',
};
const montserrat = Montserrat({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <main>{children}</main>
        </body>
      </StoreProvider>
    </html>
  );
}
