import NavigationBar from '../components/NavigationBar';
import './global.css';
import StoreProvider from '../components/StoreProvider';

export const metadata = {
  title: 'Welcome to food-blog-client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>{children}</StoreProvider>
    </html>
  );
}
