version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ protocol port
      - '15672:15672' # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./apps:/usr/src/app/apps
    command: ['sh', '-c']

  nestjs-gateway:
    build:
      context: .
      dockerfile: apps/server/nestjs-gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - builder
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/nestjs-gateway:/usr/src/app
    command: ['sh', '-c', 'node ./dist/apps/server/nestjs-gateway/main.js']

  nestjs-shop-service:
    build:
      context: .
      dockerfile: apps/server/nestjs-shop-service/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
    depends_on:
      - builder
    volumes:
      - ./apps/nestjs-shop-service:/usr/src/app
    command: ['sh', '-c', 'node ./dist/apps/server/nestjs-shop-service/main.js']
